"use client";

import { useParams } from "next/navigation";
import Link from "next/link";

export default function AdminReferencePage() {
  const params = useParams<{ section: string }>();
  const team = params.section === "team";
  return <div className="space-y-6"><div><p className="text-sm font-medium text-brand-500">Администрирование</p><h1 className="mt-1 text-2xl font-semibold text-gray-900 dark:text-white">{team ? "Команда и права" : "Категории и маршрутизация"}</h1><p className="mt-1 text-sm text-gray-500">{team ? "Учётные записи операторов и экспертов, роли и доступы." : "Справочник ситуаций и правила назначения специалистов."}</p></div><div className="flex justify-end"><button className="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-medium text-white hover:bg-brand-600">{team ? "Добавить сотрудника" : "Добавить категорию"}</button></div>{team ? <div className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-theme-sm dark:border-gray-800 dark:bg-gray-900"><div className="grid grid-cols-[1.5fr_1fr_1fr] border-b border-gray-100 px-5 py-3 text-xs font-semibold uppercase tracking-wider text-gray-400 dark:border-gray-800"><span>Сотрудник</span><span>Роль</span><span>Статус</span></div>{[["Анна Петрова", "Оператор", "Онлайн"], ["Мария Смирнова", "Психолог", "В работе"], ["Илья Волков", "Юрист", "Онлайн"], ["Ольга Ким", "Администратор", "Офлайн"]].map((row) => <div key={row[0]} className="grid grid-cols-[1.5fr_1fr_1fr] items-center border-b border-gray-100 px-5 py-4 text-sm last:border-0 dark:border-gray-800"><span className="font-medium text-gray-800 dark:text-white/90">{row[0]}</span><span className="text-gray-500">{row[1]}</span><span className={row[2] === "Онлайн" ? "text-success-600" : "text-gray-500"}>{row[2]}</span></div>)}</div> : <div className="grid gap-4 sm:grid-cols-2">{["Травля и оскорбления", "Конфликт с одноклассниками", "Кибербуллинг", "Давление и угрозы", "Конфликт с учителем", "Не знаю, как это назвать"].map((name, index) => <div key={name} className="flex items-center justify-between rounded-2xl border border-gray-200 bg-white p-5 shadow-theme-sm dark:border-gray-800 dark:bg-gray-900"><div><p className="font-medium text-gray-800 dark:text-white/90">{name}</p><p className="mt-1 text-xs text-gray-500">Группа: {index % 2 ? "Социальный педагог" : "Психолог"}</p></div><button className="text-sm text-brand-500">Изменить</button></div>)}</div>}<Link href="/" className="inline-flex text-sm font-medium text-brand-500">← Вернуться на рабочий стол</Link></div>;
}
