"use client";
import Link from "next/link";
import { useState } from "react";
import { ProductIcon } from "@/components/common/ProductUI";

const days = [{ label: "Пн", date: "14", full: "14 сентября" }, { label: "Вт", date: "15", full: "15 сентября" }, { label: "Ср", date: "16", full: "16 сентября" }, { label: "Чт", date: "17", full: "17 сентября" }, { label: "Пт", date: "18", full: "18 сентября" }, { label: "Сб", date: "19", full: "19 сентября" }, { label: "Вс", date: "20", full: "20 сентября" }];
const events = [{ time: "09:00", title: "Утренняя смена", type: "Дежурство", meta: "Разбор новых обращений", tone: "brand" }, { time: "11:30", title: "Супервизия команды", type: "Команда", meta: "Обсуждение кризисных кейсов", tone: "mint" }, { time: "14:00", title: "Синхронизация экспертов", type: "Встреча", meta: "Психолог · юрист · соцпедагог", tone: "orange" }, { time: "16:30", title: "Закрытие дня", type: "Отчёт", meta: "Проверка SLA и очереди", tone: "violet" }];

export default function CalendarPage() {
 const [selected, setSelected] = useState("14"); const [toast, setToast] = useState("");
 const notify = (text: string) => { setToast(text); window.setTimeout(() => setToast(""), 1800); };
 return <div className="ot-calendar">
  <div className="ot-calendar-header"><div><p className="ot-eyebrow">Командный ритм</p><h1>Календарь команды</h1><p className="ot-calendar-sub">Планируй смены, супервизии и контрольные точки без перегрузки.</p></div><div className="ot-calendar-actions"><button className="ot-calendar-button secondary" onClick={() => notify("Показан текущий день")}><ProductIcon name="clock"/>Сегодня</button><button className="ot-calendar-button primary" onClick={() => notify("Окно создания события готово")}><ProductIcon name="plus"/>Добавить событие</button></div></div>
  <section className="ot-calendar-board"><div className="ot-calendar-month"><button aria-label="Предыдущая неделя" onClick={() => notify("Предыдущая неделя")}>‹</button><strong>Сентябрь 2026</strong><button aria-label="Следующая неделя" onClick={() => notify("Следующая неделя")}>›</button></div><div className="ot-week-strip">{days.map((day) => <button key={day.date} className={"ot-week-day " + (selected === day.date ? "active" : "")} onClick={() => setSelected(day.date)}><span>{day.label}</span><strong>{day.date}</strong>{day.date === "14" && <i/>}</button>)}</div></section>
  <div className="ot-calendar-grid"><section className="ot-agenda"><div className="ot-agenda-head"><div><span className="ot-card-kicker">Расписание</span><h2>{days.find((day) => day.date === selected)?.full}</h2></div><span className="ot-agenda-count">{events.length} события</span></div><div className="ot-event-list">{events.map((event) => <button key={event.time} className="ot-event" onClick={() => notify(event.title)}><span className="ot-event-time">{event.time}</span><span className={"ot-event-dot tone-" + event.tone}/><span className="ot-event-main"><strong>{event.title}</strong><small>{event.type} · {event.meta}</small></span><ProductIcon name="arrow"/></button>)}</div></section><aside className="ot-calendar-side"><section className="ot-side-card"><div className="ot-side-head"><div><span className="ot-card-kicker">Состояние команды</span><h3>Сегодня онлайн</h3></div><span className="ot-online-count">3/5</span></div><div className="ot-avatars"><span>АК</span><span>МС</span><span>ИВ</span><span className="muted">+2</span></div><div className="ot-progress"><span style={{ width: "60%" }}/></div><p className="ot-side-note">Два специалиста подключатся после 14:00</p></section><section className="ot-side-card accent"><span className="ot-card-kicker">Фокус дня</span><div className="ot-focus-row"><strong>2</strong><span>кризисных обращения</span></div><div className="ot-focus-row"><strong>8</strong><span>обращений в ожидании</span></div><Link href="/queue" className="ot-admin-link">Перейти в очередь <ProductIcon name="arrow"/></Link></section></aside></div>
  {toast && <div className="ot-calendar-toast"><ProductIcon name="check"/>{toast}</div>}
 </div>;
}
