"use client";

import { useState } from "react";
import Link from "next/link";
import { PageHeading, ProductIcon } from "@/components/common/ProductUI";

const stages=["Новое","Распределено","В работе","Ответ готов"];
export default function StatusPage(){const [code,setCode]=useState("");const [open,setOpen]=useState(false);return <main className="ot-public"><div className="ot-flow">{!open?<section className="ot-panel ot-status-entry"><div className="ot-heading-symbol"><ProductIcon name="key"/></div><p className="ot-eyebrow">Личный доступ</p><h1>Проверить статус</h1><p className="ot-description">Введи трек-номер, который появился после отправки обращения.</p><input className="ot-field" style={{marginTop:24}} value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="ОТК-XXXX-XXXX"/><button className="ot-button" disabled={!code.trim()} onClick={()=>setOpen(true)}>Открыть обращение <ProductIcon name="arrow"/></button><Link href="/submit" className="ot-link" style={{justifyContent:"center",marginTop:22}}>Создать новое обращение</Link></section>:<><div className="ot-page-heading"><div className="ot-heading-symbol"><ProductIcon name="clock"/></div><div><p className="ot-eyebrow">Обращение {code||"ОТК-7M4K-2P9Q"}</p><h1>Мне угрожают одноклассники</h1><p className="ot-description">Последнее обновление сегодня в 14:32</p></div></div><div className="ot-status-grid"><section className="ot-panel"><div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"center"}}><h2>Статус обращения</h2><span className="ot-eyebrow">В работе</span></div><ol className="ot-status-list">{stages.map((s,i)=><li key={s}><span><ProductIcon name={i<3?"check":"clock"}/></span><div><strong>{s}</strong><small>{i<3?"Завершено":"Следующий этап"}</small></div></li>)}</ol><div className="ot-alert" style={{borderColor:"#d5cdf6",background:"#f6f3ff",color:"#51449f"}}><strong>Специалист разбирается в ситуации</strong><br/><span>Ответ появится здесь, а регистрация не потребуется.</span></div></section><section className="ot-panel"><h2>Диалог</h2><div className="ot-bubble">Привет. Спасибо, что поделился. Я рядом и помогу разобраться.</div><div className="ot-bubble self">В школе и в общем чате класса.</div><div className="ot-bubble">Понял. Я готовлю рекомендации и скоро вернусь с ответом.</div><div className="ot-composer"><input className="ot-field" placeholder="Написать специалисту..."/><button className="ot-button"><ProductIcon name="arrow"/></button></div></section></div><button className="ot-link" style={{marginTop:24}} onClick={()=>setOpen(false)}>← Ввести другой номер</button></>}</div></main>}

